version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: topsecret
      POSTGRES_DB: postgres
    volumes:
      - postgrescheckin:/var/lib/postgresql/data
  hasura-db:
    image: postgres:13    
    restart: always
    volumes:
    - hasuradbcheckin:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    command: -p 5433
  hasura:
    image: hasura/graphql-engine:latest
    restart: always
    ports:
    - "8080:8080"
    depends_on:
    - hasura-db
    - postgres
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@hasura-db:5433/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://prisma:topsecret@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256","key":"jQnTqVsYv2x5A7C9FcHeKhPkRnUrWtZw3y5B8DaFdJfMhQmSpVsXuZx4z6B9EbGdKgNjRnTqVtYv2x5A7C9FcHeMhPkRpUrWtZw3"}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
      # HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS: "true"
volumes:
  postgrescheckin:
  hasuradbcheckin: