/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "../../types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface CheckinContract extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): CheckinContract;
  clone(): CheckinContract;
  methods: {
    checkIn(_checkinInfo: string): NonPayableTransactionObject<void>;

    checkinCount(): NonPayableTransactionObject<string>;

    claim(): NonPayableTransactionObject<void>;

    getAddress(): NonPayableTransactionObject<string>;

    getCheckIn(
      id: number | string | BN
    ): NonPayableTransactionObject<[string, string, string, string, string]>;

    getTokenBalance(): NonPayableTransactionObject<string>;

    rewardAmount(): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
