/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as checkinSol from "./Checkin.sol";
export type { checkinSol };
import type * as tokenSol from "./Token.sol";
export type { tokenSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { EmployeeID } from "./EmployeeID";
export type { TodoList } from "./TodoList";
